[features]
seeds = false
[programs.localnet]
pyth_example = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.devnet]
pyth_example = "CE8dkMzNfG9Tfhehw6wdLM7qoYeDZTWDs19FVX7VXvLZ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/gbescos/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
